// Code generated by hertz generator.

package main

import (
	"simple-tiktok/biz/dal"
	"simple-tiktok/biz/mw"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	dal.Init()
	mw.InitJWT()
}

func main() {
	Init()
	h := server.Default(
		server.WithHostPorts(":8080"),
		server.WithMaxRequestBodySize(10*1024*1024),
	)

	register(h)
	h.Spin()
}
