// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	handler "simple-tiktok/biz/handler"
	tiktok "simple-tiktok/biz/model/tiktok"
	"simple-tiktok/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 404
		log.Println("recv request", string(c.Method()), string(c.URI().FullURI()))
		c.JSON(http.StatusOK, utils.H{
			"status_code": errno.PageNotFound.ErrCode,
			"status_msg":  errno.PageNotFound.ErrMsg,
		})
	})
	r.NoMethod(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 405
		log.Println("recv request", string(c.Method()), string(c.URI().FullURI()))
		c.JSON(http.StatusOK, utils.H{
			"status_code": errno.MethodNotAllowed.ErrCode,
			"status_msg":  errno.MethodNotAllowed.ErrMsg,
		})
	})
	r.GET("/file/", func(ctx context.Context, c *app.RequestContext) {
		var req tiktok.DownloadRequest
		err := c.BindAndValidate(&req)
		if err != nil {
			log.Printf("参数BindAndValidate失败: %v\n", err.Error())
			return
		}
		filePath := fmt.Sprintf("./file/upload/%s", req.Location)
		log.Println(filePath)
		c.File(filePath)
	})
}
