// Code generated by hertz generator.

package tiktok

import (
	"context"
	"crypto/md5"
	"fmt"
	"io"
	"log"
	"net/http"

	"simple-tiktok/biz/dal/db"
	tiktok "simple-tiktok/biz/model/tiktok"
	"simple-tiktok/biz/mw"
	"simple-tiktok/pkg/consts"
	"simple-tiktok/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
)

// CreateUser .
// @router /douyin/user/register/ [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktok.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Printf("参数BindAndValidate失败: %v\n", err.Error())
		c.JSON(http.StatusBadRequest, tiktok.CreateUserResponse{
			StatusCode: errno.ServiceErr.ErrCode,
			StatusMsg:  &errno.ServiceErr.ErrMsg,
		})
		return
	}

	users, err := db.QueryUser(ctx, req.Username)
	if err != nil {
		log.Printf("查询用户失败: %v\n", err.Error())
		c.JSON(http.StatusInternalServerError, tiktok.CreateUserResponse{
			StatusCode: errno.ServiceErr.ErrCode,
			StatusMsg:  &errno.ServiceErr.ErrMsg,
		})
		return
	}
	if len(users) != 0 {
		c.JSON(http.StatusBadRequest, tiktok.CreateUserResponse{
			StatusCode: errno.UserAlreadyExistErr.ErrCode,
			StatusMsg:  &errno.UserAlreadyExistErr.ErrMsg,
		})
		return
	}

	h := md5.New()
	if _, err = io.WriteString(h, req.Password); err != nil {
		log.Printf("md5加密错误: %v\n", err.Error())
		c.JSON(http.StatusInternalServerError, tiktok.CreateUserResponse{
			StatusCode: errno.ServiceErr.ErrCode,
			StatusMsg:  &errno.ServiceErr.ErrMsg,
		})
		return
	}

	password := fmt.Sprintf("%x", h.Sum(nil))
	uid, err := db.CreateUser(ctx, []*db.User{{
		Username: req.Username,
		Password: password,
	}})
	if err != nil {
		log.Printf("创建用户失败: %v\n", err.Error())
		c.JSON(http.StatusInternalServerError, tiktok.CreateUserResponse{
			StatusCode: errno.ServiceErr.ErrCode,
			StatusMsg:  &errno.ServiceErr.ErrMsg,
		})
		return
	}
	c.Set(consts.IdentityKey, &tiktok.User{ID: int64(uid)})
	mw.JwtMiddleware.LoginHandler(ctx, c)
}

// CheckUser .
// @router /douyin/user/login/ [POST]
func CheckUser(ctx context.Context, c *app.RequestContext) {
	mw.JwtMiddleware.LoginHandler(ctx, c)
}

// Feed .
// @router /douyin/feed/ [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktok.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(http.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktok.FeedResponse)

	c.JSON(http.StatusOK, resp)
}
