// Code generated by hertz generator.

package tiktok

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	tiktok "simple-tiktok/biz/model/tiktok"
)

// UploadComment .
// @router /douyin/comment/action/ [POST]
func UploadComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktok.CommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktok.CommentResponse)

	c.JSON(consts.StatusOK, resp)
}
