// Code generated by hertz generator.

package tiktok

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
)

// FavouriteAction
// 当前用户对视频的点赞操作 ,并把这个行为更新到like表中。
// 当前操作行为，1点赞，2取消点赞。
// @router /douyin/favorite/action/ [POST]
func FavouriteAction(ctx context.Context, c *app.RequestContext) {
	/*	var err error
		var req tiktok.FavoriteActionRequest
		err = c.BindAndValidate(&req)*/
}

// GetFavouriteList 获取当前用户的所有点赞视频，调用video_service的方法
// @router /douyin/favorite/list/ [GET]
func GetFavouriteList(ctx context.Context, c *app.RequestContext) {
	return
}
